/COE/RBP_FE_DATATYPES:
  IS_INPUT:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_FE_RFM_STRUCTURE
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IS_INPUT
    required: true
    paramType: struct
  IV_COUNT:
    PARAMCLASS: I
    TABNAME: INT4
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_COUNT
    required: false
    default: '100'
    paramType: var
  IV_DECF16:
    PARAMCLASS: I
    TABNAME: DECFLOAT16
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_DECF16
    required: false
    default: ''
    paramType: var
    nativeKey: DECFLOAT16
  IV_GENERATE:
    PARAMCLASS: I
    TABNAME: CHAR1
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_GENERATE
    required: false
    default: '''X'''
    paramType: var
  IV_LANGU:
    PARAMCLASS: I
    TABNAME: DFIES
    FIELDNAME: LANGU
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_LANGU
    required: false
    default: '''E'''
    paramType: var
  IV_LANGU_D:
    PARAMCLASS: I
    TABNAME: DDLANGUAGE
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_LANGU_D
    required: false
    default: '''E'''
    paramType: var
  IV_STRING:
    PARAMCLASS: I
    TABNAME: STRING
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_STRING
    required: false
    default: '''0123456789'''
    paramType: var
    nativeKey: STRING
  IV_STRING_SIZE:
    PARAMCLASS: I
    TABNAME: INT8
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_STRING_SIZE
    required: false
    default: '1'
    paramType: var
    nativeKey: INT8
  IV_UNAME:
    PARAMCLASS: I
    TABNAME: SYST_UNAME
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_UNAME
    required: false
    default: ''''''
    paramType: var
  IV_UNAME_DOM:
    PARAMCLASS: I
    TABNAME: SYCHAR12
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_UNAME_DOM
    required: false
    default: ''''''
    paramType: var
  IV_XSTRING:
    PARAMCLASS: I
    TABNAME: XSTRING
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_XSTRING
    required: false
    default: ''
    paramType: var
    nativeKey: XSTRING
  IV_XSTRING_SIZE:
    PARAMCLASS: I
    TABNAME: INT8
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: IV_XSTRING_SIZE
    required: false
    default: '1'
    paramType: var
    nativeKey: INT8
  CV_CKEY:
    PARAMCLASS: C
    TABNAME: WAERS
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: CV_CKEY
    required: false
    default: ''
    paramType: var
  CV_INT:
    PARAMCLASS: C
    TABNAME: INT4
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: CV_INT
    required: false
    default: ''
    paramType: var
  CS_STRUCT:
    PARAMCLASS: C
    TABNAME: /COE/RBP_S_FE_RFM_STRUCTURE
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: CS_STRUCT
    required: false
    default: ''
    paramType: struct
  CT_TABLE:
    PARAMCLASS: C
    TABNAME: /COE/RBP_T_FE_RFM_TABLE_TYPE
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: CT_TABLE
    required: false
    default: ''
    paramType: table
  ET_OUTPUT:
    PARAMCLASS: T
    TABNAME: /COE/RBP_T_FE_RFM_TABLE_TYPE
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: ET_OUTPUT
    required: true
    paramType: table
  ET_RAW:
    PARAMCLASS: T
    TABNAME: SDOKCNTBINS
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: ET_RAW
    required: true
    paramType: table
  EV_STRING:
    PARAMCLASS: E
    TABNAME: STRING
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: EV_STRING
    required: true
    paramType: var
    nativeKey: STRING
  EV_XSTRING:
    PARAMCLASS: E
    TABNAME: XSTRING
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: EV_XSTRING
    required: true
    paramType: var
    nativeKey: XSTRING
  ES_OUTPUT:
    PARAMCLASS: E
    TABNAME: /COE/RBP_S_FE_RFM_STRUCTURE
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: ES_OUTPUT
    required: true
    paramType: struct
  EX_EXCEPTION1:
    PARAMCLASS: X
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES
    paramName: EX_EXCEPTION1
    required: true
    paramType: exception
/COE/RBP_FE_DATATYPES2:
  IV_DECF16:
    PARAMCLASS: I
    TABNAME: DECFLOAT16
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: IV_DECF16
    required: false
    default: ''
    paramType: var
    nativeKey: DECFLOAT16
  IV_DECF161:
    PARAMCLASS: I
    TABNAME: DECFLOAT16
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: IV_DECF161
    required: false
    default: '''0.0'''
    paramType: var
    nativeKey: DECFLOAT16
  IV_DECF34:
    PARAMCLASS: I
    TABNAME: DECFLOAT34
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: IV_DECF34
    required: false
    default: ''
    paramType: var
    nativeKey: DECFLOAT34
  IV_INT1:
    PARAMCLASS: I
    TABNAME: INT1
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: IV_INT1
    required: false
    default: '1'
    paramType: var
  IV_INT2:
    PARAMCLASS: I
    TABNAME: INT2
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: IV_INT2
    required: false
    default: '2'
    paramType: var
  IV_INT4:
    PARAMCLASS: I
    TABNAME: INT4
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: IV_INT4
    required: false
    default: '4'
    paramType: var
  IV_INT8:
    PARAMCLASS: I
    TABNAME: INT8
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: IV_INT8
    required: false
    default: '8'
    paramType: var
    nativeKey: INT8
  EV_DECF16:
    PARAMCLASS: E
    TABNAME: DECFLOAT16
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EV_DECF16
    required: true
    paramType: var
    nativeKey: DECFLOAT16
  EV_DECF34:
    PARAMCLASS: E
    TABNAME: DECFLOAT34
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EV_DECF34
    required: true
    paramType: var
    nativeKey: DECFLOAT34
  EV_INT1:
    PARAMCLASS: E
    TABNAME: INT1
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EV_INT1
    required: true
    paramType: var
  EV_INT2:
    PARAMCLASS: E
    TABNAME: INT2
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EV_INT2
    required: true
    paramType: var
  EV_INT4:
    PARAMCLASS: E
    TABNAME: INT4
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EV_INT4
    required: true
    paramType: var
  EV_INT8:
    PARAMCLASS: E
    TABNAME: INT8
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EV_INT8
    required: true
    paramType: var
    nativeKey: INT8
  EXP_ISSUE115:
    PARAMCLASS: E
    TABNAME: /COE/TT_TABNAME
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EXP_ISSUE115
    required: true
    paramType: table
  EX_EXCEPTION1:
    PARAMCLASS: X
    PARAMTEXT: ''
    functionName: /COE/RBP_FE_DATATYPES2
    paramName: EX_EXCEPTION1
    required: true
    paramType: exception
