/COE/RBP_PAM_NOTIF_CHANGE:
  IV_NOTIFNO:
    PARAMCLASS: I
    TABNAME: QMNUM
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: IV_NOTIFNO
    required: true
    paramType: var
  IS_NOTIF_HEADER:
    PARAMCLASS: I
    TABNAME: BAPI2080_NOTHDRI
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: IS_NOTIF_HEADER
    required: true
    paramType: struct
  IV_NEW_NOTICE:
    PARAMCLASS: I
    TABNAME: STRING
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: IV_NEW_NOTICE
    required: false
    default: ''
    paramType: var
    nativeKey: STRING
  IS_NOTIF_HEADER_X:
    PARAMCLASS: I
    TABNAME: BAPI2080_NOTHDRI_X
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: IS_NOTIF_HEADER_X
    required: false
    default: ''
    paramType: struct
  CT_EXTENSIONIN:
    PARAMCLASS: C
    TABNAME: BAPIPAREX_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_EXTENSIONIN
    required: false
    default: ''
    paramType: table
  CT_EXTENSIONOUT:
    PARAMCLASS: C
    TABNAME: BAPIPAREX_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_EXTENSIONOUT
    required: false
    default: ''
    paramType: table
  CT_NOTIFACTV:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTACTVI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFACTV
    required: false
    default: ''
    paramType: table
  CT_NOTIFACTV_X:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTACTVI_X_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFACTV_X
    required: false
    default: ''
    paramType: table
  CT_NOTIFCAUS:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTCAUSI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFCAUS
    required: false
    default: ''
    paramType: table
  CT_NOTIFCAUS_X:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTCAUSI_X_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFCAUS_X
    required: false
    default: ''
    paramType: table
  CT_NOTIFPARTNR:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTPARTNRI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFPARTNR
    required: false
    default: ''
    paramType: table
  CT_NOTIFPARTNR_X:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTPARTNRI_X_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFPARTNR_X
    required: false
    default: ''
    paramType: table
  CT_NOTIFTASK:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTTASKI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFTASK
    required: false
    default: ''
    paramType: table
  CT_NOTIFTASK_X:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTTASKI_X_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTIFTASK_X
    required: false
    default: ''
    paramType: table
  CT_NOTITEM:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTITEMI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTITEM
    required: false
    default: ''
    paramType: table
  CT_NOTITEM_X:
    PARAMCLASS: C
    TABNAME: EAML_BAPI2080_NOTITEMI_X_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: CT_NOTITEM_X
    required: false
    default: ''
    paramType: table
  ES_NOTIF_HEADER:
    PARAMCLASS: E
    TABNAME: BAPI2080_NOTHDRE
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: ES_NOTIF_HEADER
    required: true
    paramType: struct
  ET_NOTICE:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_NOTICE_LOG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: ET_NOTICE
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRETTAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: ET_RETURN
    required: true
    paramType: table
  ET_SYSSTATUS:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_SYSSTATUS
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CHANGE
    paramName: ET_SYSSTATUS
    required: true
    paramType: table
/COE/RBP_PAM_NOTIF_CREATE:
  IV_NOTIF_TYPE:
    PARAMCLASS: I
    TABNAME: QMART
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: IV_NOTIF_TYPE
    required: true
    paramType: var
  IS_NOTIF_HEADER_IN:
    PARAMCLASS: I
    TABNAME: BAPI2080_NOTHDRI
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: IS_NOTIF_HEADER_IN
    required: true
    paramType: struct
  IV_NEW_NOTICE:
    PARAMCLASS: I
    TABNAME: STRING
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: IV_NEW_NOTICE
    required: false
    default: ''
    paramType: var
    nativeKey: STRING
  CT_EXTENSIONIN:
    PARAMCLASS: C
    TABNAME: BAPIPAREX_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_EXTENSIONIN
    required: false
    default: ''
    paramType: table
  CT_EXTENSIONOUT:
    PARAMCLASS: C
    TABNAME: BAPIPAREX_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_EXTENSIONOUT
    required: false
    default: ''
    paramType: table
  CT_KEY_RELATIONSHIPS:
    PARAMCLASS: C
    TABNAME: /COE/BAPI2080_NOTKEYE_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_KEY_RELATIONSHIPS
    required: false
    default: ''
    paramType: table
  CT_NOTIFACTV:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTACTVI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_NOTIFACTV
    required: false
    default: ''
    paramType: table
  CT_NOTIFCAUS:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTCAUSI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_NOTIFCAUS
    required: false
    default: ''
    paramType: table
  CT_NOTIFPARTNR:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTPARTNRI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_NOTIFPARTNR
    required: false
    default: ''
    paramType: table
  CT_NOTIFTASK:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTTASKI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_NOTIFTASK
    required: false
    default: ''
    paramType: table
  CT_NOTITEM:
    PARAMCLASS: C
    TABNAME: ALM_ME_BAPI2080_NOTITEMI_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: CT_NOTITEM
    required: false
    default: ''
    paramType: table
  ES_NOTIF_HEADER_OUT:
    PARAMCLASS: E
    TABNAME: BAPI2080_NOTHDRE
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: ES_NOTIF_HEADER_OUT
    required: true
    paramType: struct
  ET_NOTICE:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_NOTICE_LOG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: ET_NOTICE
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRETTAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: ET_RETURN
    required: true
    paramType: table
  ET_SYSSTATUS:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_SYSSTATUS
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIF_CREATE
    paramName: ET_SYSSTATUS
    required: true
    paramType: table
/COE/RBP_PAM_NOTIFICATION_GET:
  IV_NOTIFNO:
    PARAMCLASS: I
    TABNAME: QMNUM
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: IV_NOTIFNO
    required: true
    paramType: var
  IV_DOCUMENT:
    PARAMCLASS: I
    TABNAME: FLAG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: IV_DOCUMENT
    required: false
    default: ''
    paramType: var
  ES_HEADER:
    PARAMCLASS: E
    TABNAME: BAPI2080_NOTHDRE
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ES_HEADER
    required: true
    paramType: struct
  ET_DOCUMENT:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_DOCUMENT
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_DOCUMENT
    required: true
    paramType: table
  ET_EXTENSIONOUT:
    PARAMCLASS: E
    TABNAME: BAPIPAREX_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_EXTENSIONOUT
    required: true
    paramType: table
  ET_NOTICE:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_NOTICE_LOG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_NOTICE
    required: true
    paramType: table
  ET_NOTIFACTV:
    PARAMCLASS: E
    TABNAME: ALM_ME_BAPI2080_NOTACTVE_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_NOTIFACTV
    required: true
    paramType: table
  ET_NOTIFCAUS:
    PARAMCLASS: E
    TABNAME: ALM_ME_BAPI2080_NOTCAUSE_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_NOTIFCAUS
    required: true
    paramType: table
  ET_NOTIFPARTNR:
    PARAMCLASS: E
    TABNAME: ALM_ME_BAPI2080_NOTPARTNRE_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_NOTIFPARTNR
    required: true
    paramType: table
  ET_NOTIFTASK:
    PARAMCLASS: E
    TABNAME: ALM_ME_BAPI2080_NOTTASKE_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_NOTIFTASK
    required: true
    paramType: table
  ET_NOTITEM:
    PARAMCLASS: E
    TABNAME: ALM_ME_BAPI2080_NOTITEME_T
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_NOTITEM
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRETTAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_RETURN
    required: true
    paramType: table
  ET_SYSSTATUS:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_SYSSTATUS
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GET
    paramName: ET_SYSSTATUS
    required: true
    paramType: table
/COE/RBP_PAM_NOTIFICATION_GETL:
  IV_COMPLETE:
    PARAMCLASS: I
    TABNAME: BAPI2080_2
    FIELDNAME: COMPLETE
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IV_COMPLETE
    required: false
    default: '''X'''
    paramType: var
  IV_IN_PROCESS:
    PARAMCLASS: I
    TABNAME: DY_IAR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IV_IN_PROCESS
    required: false
    default: '''X'''
    paramType: var
  IV_NOTIFICATION_DATE:
    PARAMCLASS: I
    TABNAME: BAPI2080_1
    FIELDNAME: NOTIFDATE
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IV_NOTIFICATION_DATE
    required: false
    default: SY-DATUM
    paramType: var
  IV_OUTSTANDING:
    PARAMCLASS: I
    TABNAME: DY_OFN
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IV_OUTSTANDING
    required: false
    default: '''X'''
    paramType: var
  IV_POSTPONED:
    PARAMCLASS: I
    TABNAME: DY_RST
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IV_POSTPONED
    required: false
    default: '''X'''
    paramType: var
  IS_CUSTOMER:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_NOTIF_CUSTOMER
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IS_CUSTOMER
    required: false
    default: ''
    paramType: struct
  IS_EQUIPMENT:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_NOTIF_EQUI
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IS_EQUIPMENT
    required: false
    default: ''
    paramType: struct
  IS_FUNCLOC:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_NOTIF_FUNCLOC
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IS_FUNCLOC
    required: false
    default: ''
    paramType: struct
  IS_PARTNER:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_NOTIF_PARTNER
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IS_PARTNER
    required: false
    default: ''
    paramType: struct
  IS_PLANGROUP:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_NOTIF_PLANGRP
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IS_PLANGROUP
    required: false
    default: ''
    paramType: struct
  IS_SORTFIELD:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_NOTIF_SORTF
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: IS_SORTFIELD
    required: false
    default: ''
    paramType: struct
  ET_NOTIFICATION:
    PARAMCLASS: T
    TABNAME: EAMS_T_BAPI2080_1
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: ET_NOTIFICATION
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRET2_TAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_NOTIFICATION_GETL
    paramName: ET_RETURN
    required: true
    paramType: table
