/COE/RBP_PAM_EQUIP_HIER_GET:
  IV_LOCATION:
    PARAMCLASS: I
    TABNAME: TPLNR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIP_HIER_GET
    paramName: IV_LOCATION
    required: true
    paramType: var
  IV_DEF_VAL:
    PARAMCLASS: I
    TABNAME: BOOLEAN
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIP_HIER_GET
    paramName: IV_DEF_VAL
    required: false
    default: ''
    paramType: var
  IV_EQUIP_TYPE:
    PARAMCLASS: I
    TABNAME: MATKL
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIP_HIER_GET
    paramName: IV_EQUIP_TYPE
    required: false
    default: ''
    paramType: var
  ET_DEF_VAL:
    PARAMCLASS: T
    TABNAME: /COE/RBP_T_PAM_DEF_VALS_EQ
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIP_HIER_GET
    paramName: ET_DEF_VAL
    required: true
    paramType: table
  ET_EQUIP_LIST:
    PARAMCLASS: T
    TABNAME: /COE/RBP_T_PAM_EQUI_DAT_HIER_L
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIP_HIER_GET
    paramName: ET_EQUIP_LIST
    required: true
    paramType: table
  ET_FUNC_LOC_LIST:
    PARAMCLASS: T
    TABNAME: /COE/RBP_T_PAM_FUNC_LOC_EQUI_L
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIP_HIER_GET
    paramName: ET_FUNC_LOC_LIST
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: T
    TABNAME: BAPIRET2_TAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIP_HIER_GET
    paramName: ET_RETURN
    required: true
    paramType: table
/COE/RBP_PAM_EQUIPMENT_CHANGE:
  IV_EQUIID:
    PARAMCLASS: I
    TABNAME: EQUNR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_CHANGE
    paramName: IV_EQUIID
    required: true
    paramType: var
  IS_DATA_SPECIFIC:
    PARAMCLASS: I
    TABNAME: BAPI_ITOB_EQ_ONLY
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_CHANGE
    paramName: IS_DATA_SPECIFIC
    required: true
    paramType: struct
  IS_DATA_SPECIFIC_X:
    PARAMCLASS: I
    TABNAME: BAPI_ITOB_EQ_ONLYX
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_CHANGE
    paramName: IS_DATA_SPECIFIC_X
    required: true
    paramType: struct
  IS_HEADER:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_EQUI_HEADER
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_CHANGE
    paramName: IS_HEADER
    required: true
    paramType: struct
  IS_HEADER_X:
    PARAMCLASS: I
    TABNAME: /COE/RBP_S_PAM_EQUI_HEADERX
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_CHANGE
    paramName: IS_HEADER_X
    required: true
    paramType: struct
  IT_CHARACTERISTICS:
    PARAMCLASS: I
    TABNAME: /COE/RBP_T_PAM_CHARACT_FOR_CHG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_CHANGE
    paramName: IT_CHARACTERISTICS
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRET2_TAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_CHANGE
    paramName: ET_RETURN
    required: true
    paramType: table
/COE/RBP_PAM_EQUIPMENT_DISMTLE:
  IV_EQUIID:
    PARAMCLASS: I
    TABNAME: EQUNR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_DISMTLE
    paramName: IV_EQUIID
    required: false
    default: ''
    paramType: var
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRET2_TAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_DISMTLE
    paramName: ET_RETURN
    required: true
    paramType: table
/COE/RBP_PAM_EQUIPMENT_GET:
  IV_CHARACTERISTICS:
    PARAMCLASS: I
    TABNAME: FLAG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: IV_CHARACTERISTICS
    required: false
    default: ''
    paramType: var
  IV_DOCUMENT:
    PARAMCLASS: I
    TABNAME: FLAG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: IV_DOCUMENT
    required: false
    default: ''
    paramType: var
  IV_EQUIID:
    PARAMCLASS: I
    TABNAME: EQUNR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: IV_EQUIID
    required: false
    default: ''
    paramType: var
  IV_WITH_TIMESTATS:
    PARAMCLASS: I
    TABNAME: FLAG
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: IV_WITH_TIMESTATS
    required: false
    default: ''
    paramType: var
  ES_HEADER:
    PARAMCLASS: E
    TABNAME: /COE/RBP_S_PAM_EQUI_HEADER
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ES_HEADER
    required: true
    paramType: struct
  ES_SPECIFIC:
    PARAMCLASS: E
    TABNAME: BAPI_ITOB_EQ_ONLY
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ES_SPECIFIC
    required: true
    paramType: struct
  ET_BRKDWN_EFF:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_MCIT_BRKDWN_EFF
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_BRKDWN_EFF
    required: true
    paramType: table
  ET_BRKDWN_REP:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_MCIT_BRKDWN_REP
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_BRKDWN_REP
    required: true
    paramType: table
  ET_CHARACT_GROUP:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_CHARACT_GROUP
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_CHARACT_GROUP
    required: true
    paramType: table
  ET_CHARACTERISTICS:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_CHARACTERISTICS
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_CHARACTERISTICS
    required: true
    paramType: table
  ET_DOCUMENT:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_DOCUMENT
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_DOCUMENT
    required: true
    paramType: table
  ET_MCIQMADD:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_MCIQMADD
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_MCIQMADD
    required: true
    paramType: table
  ET_RESULT:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_MCIT_RESULT
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_RESULT
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRET2_TAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_RETURN
    required: true
    paramType: table
  ET_STARTUP_EQUI:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_MCIT_STARTUP_EQUI
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_STARTUP_EQUI
    required: true
    paramType: table
  ET_STARTUP_IFLO:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_MCIT_STARTUP_IFLO
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_STARTUP_IFLO
    required: true
    paramType: table
  ET_USER_STATUS:
    PARAMCLASS: E
    TABNAME: CWD_TT_ITOB_STATUS
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GET
    paramName: ET_USER_STATUS
    required: true
    paramType: table
/COE/RBP_PAM_EQUIPMENT_GETL:
  IV_EQUIPMENT_DESCR:
    PARAMCLASS: I
    TABNAME: KTX01
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GETL
    paramName: IV_EQUIPMENT_DESCR
    required: false
    default: ''
    paramType: var
  IV_FUNC_LOC:
    PARAMCLASS: I
    TABNAME: TPLNR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GETL
    paramName: IV_FUNC_LOC
    required: false
    default: ''
    paramType: var
  IV_PLANT:
    PARAMCLASS: I
    TABNAME: WERKS_D
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GETL
    paramName: IV_PLANT
    required: false
    default: ''
    paramType: var
  ET_EQUIPMENT:
    PARAMCLASS: E
    TABNAME: /COE/RBP_T_PAM_EQUIPMENT
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GETL
    paramName: ET_EQUIPMENT
    required: true
    paramType: table
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRET2_TAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_GETL
    paramName: ET_RETURN
    required: true
    paramType: table
/COE/RBP_PAM_EQUIPMENT_INSTALL:
  IV_EQUIID:
    PARAMCLASS: I
    TABNAME: EQUNR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_INSTALL
    paramName: IV_EQUIID
    required: false
    default: ''
    paramType: var
  IV_FUNC_LOCATION:
    PARAMCLASS: I
    TABNAME: TPLNR
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_INSTALL
    paramName: IV_FUNC_LOCATION
    required: false
    default: ''
    paramType: var
  ET_RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRET2_TAB
    PARAMTEXT: ''
    functionName: /COE/RBP_PAM_EQUIPMENT_INSTALL
    paramName: ET_RETURN
    required: true
    paramType: table
BAPI_EQUI_CREATE:
  DATA_GENERAL:
    PARAMCLASS: I
    TABNAME: BAPI_ITOB
    PARAMTEXT: General Data for Technical Objects
    functionName: BAPI_EQUI_CREATE
    paramName: DATA_GENERAL
    required: true
    paramType: struct
  DATA_SPECIFIC:
    PARAMCLASS: I
    TABNAME: BAPI_ITOB_EQ_ONLY
    PARAMTEXT: Equipment-Specific data
    functionName: BAPI_EQUI_CREATE
    paramName: DATA_SPECIFIC
    required: true
    paramType: struct
  EXTERNAL_NUMBER:
    PARAMCLASS: I
    TABNAME: BAPI_ITOB_PARMS
    FIELDNAME: EQUIPMENT
    PARAMTEXT: Number of Equipment to be Created (Initial => Internal Assignment)
    functionName: BAPI_EQUI_CREATE
    paramName: EXTERNAL_NUMBER
    required: false
    default: ''
    paramType: var
  VALID_DATE:
    PARAMCLASS: I
    TABNAME: BAPI_ITOB_PARMS
    FIELDNAME: INST_DATE
    PARAMTEXT: Valid-From Date for Equipment to be Created
    functionName: BAPI_EQUI_CREATE
    paramName: VALID_DATE
    required: false
    default: SY-DATUM
    paramType: var
  DATA_FLEET:
    PARAMCLASS: I
    TABNAME: BAPI_FLEET
    PARAMTEXT: Vehicle-Specific Data
    functionName: BAPI_EQUI_CREATE
    paramName: DATA_FLEET
    required: false
    default: ''
    paramType: struct
  DATA_INSTALL:
    PARAMCLASS: I
    TABNAME: BAPI_ITOB_EQ_INSTALL
    PARAMTEXT: Installation Date for Equipment
    functionName: BAPI_EQUI_CREATE
    paramName: DATA_INSTALL
    required: false
    default: ''
    paramType: struct
  EXTENSIONIN:
    PARAMCLASS: T
    TABNAME: BAPIPAREX
    PARAMTEXT: Reference Structure for BAPI Parameters ExtensionIn/ExtensionOut
    functionName: BAPI_EQUI_CREATE
    paramName: EXTENSIONIN
    required: false
    default: ''
    paramType: table
  EXTENSIONOUT:
    PARAMCLASS: T
    TABNAME: BAPIPAREX
    PARAMTEXT: Reference Structure for BAPI Parameters ExtensionIn/ExtensionOut
    functionName: BAPI_EQUI_CREATE
    paramName: EXTENSIONOUT
    required: false
    default: ''
    paramType: table
  EQUIPMENT:
    PARAMCLASS: E
    TABNAME: BAPI_ITOB_PARMS
    FIELDNAME: EQUIPMENT
    PARAMTEXT: Number of Equipment Created
    functionName: BAPI_EQUI_CREATE
    paramName: EQUIPMENT
    required: true
    paramType: var
  DATA_FLEET_EXP:
    PARAMCLASS: E
    TABNAME: BAPI_FLEET
    PARAMTEXT: Vehicle-Specific Data
    functionName: BAPI_EQUI_CREATE
    paramName: DATA_FLEET_EXP
    required: true
    paramType: struct
  DATA_GENERAL_EXP:
    PARAMCLASS: E
    TABNAME: BAPI_ITOB
    PARAMTEXT: General Data for Technical Objects
    functionName: BAPI_EQUI_CREATE
    paramName: DATA_GENERAL_EXP
    required: true
    paramType: struct
  DATA_SPECIFIC_EXP:
    PARAMCLASS: E
    TABNAME: BAPI_ITOB_EQ_ONLY
    PARAMTEXT: Equipment-Specific data
    functionName: BAPI_EQUI_CREATE
    paramName: DATA_SPECIFIC_EXP
    required: true
    paramType: struct
  RETURN:
    PARAMCLASS: E
    TABNAME: BAPIRET2
    PARAMTEXT: Return Parameter
    functionName: BAPI_EQUI_CREATE
    paramName: RETURN
    required: true
    paramType: struct
