// SPDX-FileCopyrightText: 2014 SAP SE Srdjan Boskovic <srdjan.boskovic@sap.com>
//
// SPDX-License-Identifier: Apache-2.0

const ValueInputHelp = require("../dist").ValueInputHelp;
const setup = require("./setup");

("use strict");

let VI;
beforeAll(async () => {
  const vi = await ValueInputHelp.new(setup.client, setup.shlpApi);
  return (VI = vi);
});

describe("SH VBELN", () => {
  test("SH CC_VBELN", async () => {
    expect.assertions(2);
    const shlpId = { type: "SH", name: "CC_VBELN" };

    const desc = await VI.getShlpDescriptor(shlpId);
    // elementary helps
    expect(Object.keys(desc)).toEqual([
      "SH VMVAA",
      "SH VMVAB",
      "SH VMVAC",
      "SH VMVAD",
      "SH VMVAE",
      "SH VMVAF",
      "SH VMVAH",
      "SH VMVAI",
      "SH VMVAM",
      "SH VMVAN",
      "SH VMVMO_E",
      "SH VMVA_SE_SIMPLE",
      "SH VMVA_SE_ADVANCED",
      "SH VMVA_ES_SIMPLE",
      "SH VMVA_ES_ADVANCED",
      "SH WRF_SALES_MAT_CHAR",
      "SH CS_KDST",
    ]);

    const sel = [
      //["AUART", "I", "EQ", "OR", ""],
      ["BSTKD", "I", "EQ", "212345678", ""],
      ["VKORG", "I", "EQ", "1000", ""],
    ];

    const R = await VI.search({ type: "SH", name: "VMVAA" }, sel);

    expect(R).toMatchObject({
      search_result: [
        {
          BSTKD: "212345678",
          VKORG: "1000",
          KUNNR: "100000",
          VTWEG: "10",
          SPART: "10",
          VKBUR: "",
          VKGRP: "",
          ERNAM: "D029401",
          AUART: "ZTA",
          BSTDK: "00.00.0000",
          TRVOG: "0",
          VBELN: "23",
          POSNR: "000000",
        },
      ],
      shlpoutput: "VBELN",
      maxrows_exceeded: false,
      headers: [
        {
          field: "BSTKD",
          len: 35,
          abaptype: "CHAR",
          title: "Purchase order no.",
          text_align: "left",
          position: "",
        },
        {
          field: "VKORG",
          len: 4,
          abaptype: "CHAR",
          title: "SOrg.",
          text_align: "left",
          position: "",
        },
        {
          field: "KUNNR",
          len: 10,
          abaptype: "CHAR",
          title: "Sold-to pt",
          text_align: "left",
          position: "",
        },
        {
          field: "VTWEG",
          len: 2,
          abaptype: "CHAR",
          title: "DChl",
          text_align: "left",
          position: "",
        },
        {
          field: "SPART",
          len: 2,
          abaptype: "CHAR",
          title: "Dv",
          text_align: "left",
          position: "",
        },
        {
          field: "VKBUR",
          len: 4,
          abaptype: "CHAR",
          title: "SOff.",
          text_align: "left",
          position: "",
        },
        {
          field: "VKGRP",
          len: 3,
          abaptype: "CHAR",
          title: "SGrp",
          text_align: "left",
          position: "",
        },
        {
          field: "ERNAM",
          len: 12,
          abaptype: "CHAR",
          title: "Created by",
          text_align: "left",
          position: "",
        },
        {
          field: "AUART",
          len: 4,
          abaptype: "CHAR",
          title: "SaTy",
          text_align: "left",
          position: "",
        },
        {
          field: "BSTDK",
          len: 8,
          abaptype: "DATS",
          title: "PO date",
          text_align: "left",
          position: "",
        },
        {
          field: "TRVOG",
          len: 1,
          abaptype: "CHAR",
          title: "TrG",
          text_align: "left",
          position: "",
        },
        {
          field: "POSNR",
          len: 6,
          abaptype: "NUMC",
          title: "Item",
          text_align: "left",
          position: "",
        },
        {
          field: "VBELN",
          len: 10,
          abaptype: "CHAR",
          title: "Document",
          text_align: "left",
          position: "",
        },
      ],
      desc: [
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "BSTKD",
          LANGU: "E",
          POSITION: "0001",
          OFFSET: "000006",
          DOMNAME: "CHAR35",
          ROLLNAME: "BSTKD_M",
          CHECKTABLE: "",
          LENG: "000035",
          INTLEN: "000070",
          OUTPUTLEN: "000035",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "",
          LOGFLAG: "",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "35",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Customer PO number as matchcode field",
          REPTEXT: "Purchase order no.",
          SCRTEXT_S: "Pur. Order",
          SCRTEXT_M: "PO Number",
          SCRTEXT_L: "Purchase order no.",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "",
          COMPTYPE: "E",
          LFIELDNAME: "BSTKD",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "VKORG",
          LANGU: "E",
          POSITION: "0002",
          OFFSET: "000076",
          DOMNAME: "VKORG",
          ROLLNAME: "VKORG",
          CHECKTABLE: "TVKO",
          LENG: "000004",
          INTLEN: "000008",
          OUTPUTLEN: "000004",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "VKO",
          LOGFLAG: "X",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "05",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Sales Organization",
          REPTEXT: "SOrg.",
          SCRTEXT_S: "Sales org.",
          SCRTEXT_M: "Sales Org.",
          SCRTEXT_L: "Sales Organization",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "VKORG",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "KUNNR",
          LANGU: "E",
          POSITION: "0003",
          OFFSET: "000084",
          DOMNAME: "KUNNR",
          ROLLNAME: "KUNAG",
          CHECKTABLE: "KNA1",
          LENG: "000010",
          INTLEN: "000020",
          OUTPUTLEN: "000010",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "VAG",
          LOGFLAG: "X",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "ALPHA",
          HEADLEN: "10",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Sold-to party",
          REPTEXT: "Sold-to pt",
          SCRTEXT_S: "Sold-to pt",
          SCRTEXT_M: "Sold-to party",
          SCRTEXT_L: "Sold-to party",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "KUNNR",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "VTWEG",
          LANGU: "E",
          POSITION: "0004",
          OFFSET: "000104",
          DOMNAME: "VTWEG",
          ROLLNAME: "VTWEG",
          CHECKTABLE: "TVKOV",
          LENG: "000002",
          INTLEN: "000004",
          OUTPUTLEN: "000002",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "VTW",
          LOGFLAG: "X",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "04",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Distribution Channel",
          REPTEXT: "DChl",
          SCRTEXT_S: "Distr. Chl",
          SCRTEXT_M: "Distr. Channel",
          SCRTEXT_L: "Distribution Channel",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "VTWEG",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "SPART",
          LANGU: "E",
          POSITION: "0005",
          OFFSET: "000108",
          DOMNAME: "SPART",
          ROLLNAME: "SPART",
          CHECKTABLE: "TVTA",
          LENG: "000002",
          INTLEN: "000004",
          OUTPUTLEN: "000002",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "SPA",
          LOGFLAG: "X",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "02",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Division",
          REPTEXT: "Dv",
          SCRTEXT_S: "Division",
          SCRTEXT_M: "Division",
          SCRTEXT_L: "Division",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "SPART",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "VKBUR",
          LANGU: "E",
          POSITION: "0006",
          OFFSET: "000112",
          DOMNAME: "VKBUR",
          ROLLNAME: "VKBUR",
          CHECKTABLE: "TVKBZ",
          LENG: "000004",
          INTLEN: "000008",
          OUTPUTLEN: "000004",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "VKB",
          LOGFLAG: "X",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "05",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Sales office",
          REPTEXT: "SOff.",
          SCRTEXT_S: "Sales off.",
          SCRTEXT_M: "Sales office",
          SCRTEXT_L: "Sales office",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "VKBUR",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "VKGRP",
          LANGU: "E",
          POSITION: "0007",
          OFFSET: "000120",
          DOMNAME: "VKGRP",
          ROLLNAME: "VKGRP",
          CHECKTABLE: "TVBVK",
          LENG: "000003",
          INTLEN: "000006",
          OUTPUTLEN: "000003",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "VKG",
          LOGFLAG: "X",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "04",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Sales group",
          REPTEXT: "SGrp",
          SCRTEXT_S: "Sales grp",
          SCRTEXT_M: "Sales group",
          SCRTEXT_L: "Sales group",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "VKGRP",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "ERNAM",
          LANGU: "E",
          POSITION: "0008",
          OFFSET: "000126",
          DOMNAME: "USNAM",
          ROLLNAME: "ERNAM",
          CHECKTABLE: "",
          LENG: "000012",
          INTLEN: "000024",
          OUTPUTLEN: "000012",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "",
          LOGFLAG: "",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "12",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Name of Person who Created the Object",
          REPTEXT: "Created by",
          SCRTEXT_S: "Created",
          SCRTEXT_M: "Created by",
          SCRTEXT_L: "Created by",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "",
          COMPTYPE: "E",
          LFIELDNAME: "ERNAM",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "AUART",
          LANGU: "E",
          POSITION: "0009",
          OFFSET: "000150",
          DOMNAME: "AUART",
          ROLLNAME: "AUART",
          CHECKTABLE: "TVAK",
          LENG: "000004",
          INTLEN: "000008",
          OUTPUTLEN: "000004",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "AAT",
          LOGFLAG: "",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "AUART",
          HEADLEN: "04",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Sales Document Type",
          REPTEXT: "SaTy",
          SCRTEXT_S: "SalesDocTy",
          SCRTEXT_M: "Sales doc. type",
          SCRTEXT_L: "Sales document type",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "AUART",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "BSTDK",
          LANGU: "E",
          POSITION: "0010",
          OFFSET: "000158",
          DOMNAME: "DATUM",
          ROLLNAME: "BSTDK",
          CHECKTABLE: "",
          LENG: "000008",
          INTLEN: "000016",
          OUTPUTLEN: "000010",
          DECIMALS: "000000",
          DATATYPE: "DATS",
          INTTYPE: "D",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "",
          LOGFLAG: "X",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "10",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Customer purchase order date",
          REPTEXT: "PO date",
          SCRTEXT_S: "PO date",
          SCRTEXT_M: "PO date",
          SCRTEXT_L: "Purchase order date",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "BSTDK",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "TRVOG",
          LANGU: "E",
          POSITION: "0011",
          OFFSET: "000174",
          DOMNAME: "TRVOG",
          ROLLNAME: "TRVOG",
          CHECKTABLE: "",
          LENG: "000001",
          INTLEN: "000002",
          OUTPUTLEN: "000001",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "VTV",
          LOGFLAG: "",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "03",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Transaction group",
          REPTEXT: "TrG",
          SCRTEXT_S: "Trans.Grp",
          SCRTEXT_M: "Transact.group",
          SCRTEXT_L: "Transaction group",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "X",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "TRVOG",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "VBELN",
          LANGU: "E",
          POSITION: "0013",
          OFFSET: "000188",
          DOMNAME: "VBELN",
          ROLLNAME: "VBELN",
          CHECKTABLE: "",
          LENG: "000010",
          INTLEN: "000020",
          OUTPUTLEN: "000010",
          DECIMALS: "000000",
          DATATYPE: "CHAR",
          INTTYPE: "C",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "VBELN",
          AUTHORID: "",
          MEMORYID: "AUN",
          LOGFLAG: "",
          MASK: "  X",
          MASKLEN: "0000",
          CONVEXIT: "ALPHA",
          HEADLEN: "10",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Sales and Distribution Document Number",
          REPTEXT: "Document",
          SCRTEXT_S: "SD Doc.",
          SCRTEXT_M: "Sales document",
          SCRTEXT_L: "Sales document",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "",
          COMPTYPE: "D",
          LFIELDNAME: "",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
        {
          TABNAME: "M_VMVAA",
          FIELDNAME: "POSNR",
          LANGU: "E",
          POSITION: "0012",
          OFFSET: "000176",
          DOMNAME: "POSNR",
          ROLLNAME: "POSNR",
          CHECKTABLE: "VBUP",
          LENG: "000006",
          INTLEN: "000012",
          OUTPUTLEN: "000006",
          DECIMALS: "000000",
          DATATYPE: "NUMC",
          INTTYPE: "N",
          REFTABLE: "",
          REFFIELD: "",
          PRECFIELD: "M_VMVAA",
          AUTHORID: "",
          MEMORYID: "",
          LOGFLAG: "",
          MASK: "",
          MASKLEN: "0000",
          CONVEXIT: "",
          HEADLEN: "06",
          SCRLEN1: "10",
          SCRLEN2: "15",
          SCRLEN3: "20",
          FIELDTEXT: "Item number of the SD document",
          REPTEXT: "Item",
          SCRTEXT_S: "Item",
          SCRTEXT_M: "Item",
          SCRTEXT_L: "Item (SD)",
          KEYFLAG: "X",
          LOWERCASE: "",
          MAC: "",
          GENKEY: "",
          NOFORKEY: "",
          VALEXI: "",
          NOAUTHCH: "",
          SIGN: "",
          DYNPFLD: "X",
          F4AVAILABL: "X",
          COMPTYPE: "E",
          LFIELDNAME: "POSNR",
          LTRFLDDIS: "",
          BIDICTRLC: "",
          OUTPUTSTYLE: "00",
          NOHISTORY: "",
          AMPMFORMAT: "",
        },
      ],
    });
  });

  test("Getters: title not found", async () => {
    expect.assertions(1);
    const shlpId = {
      type: "SH",
      name: "XYZ",
    };
    try {
      const title = VI.getShlpTitle(shlpId);
    } catch (ex) {
      expect(ex).toEqual(new Error(`Shlp title not found: "SH XYZ"`));
    }
  });

  test("Getters: title, parameters", async () => {
    expect.assertions(2);
    const shlpId = {
      type: "SH",
      name: "VMVAA",
    };
    const desc = await VI.getShlpDescriptor(shlpId, { noCache: true });

    const title = VI.getShlpTitle(shlpId);
    expect(title).toEqual("Sales document according to customer PO number");

    const params = VI.getShlpParams(shlpId);
    expect(params).toEqual([
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "BSTKD",
        LANGU: "E",
        POSITION: 1,
        OFFSET: 6,
        DOMNAME: "CHAR35",
        ROLLNAME: "BSTKD_M",
        CHECKTABLE: "",
        LENG: 35,
        INTLEN: 70,
        OUTPUTLEN: 35,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "",
        LOGFLAG: "",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 35,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Customer PO number as matchcode field",
        REPTEXT: "Purchase order no.",
        SCRTEXT_S: "Pur. Order",
        SCRTEXT_M: "PO Number",
        SCRTEXT_L: "Purchase order no.",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "",
        COMPTYPE: "E",
        LFIELDNAME: "BSTKD",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "01",
        SHLPLISPOS: "01",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "VKORG",
        LANGU: "E",
        POSITION: 2,
        OFFSET: 76,
        DOMNAME: "VKORG",
        ROLLNAME: "VKORG",
        CHECKTABLE: "TVKO",
        LENG: 4,
        INTLEN: 8,
        OUTPUTLEN: 4,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "VKO",
        LOGFLAG: "X",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 5,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Sales Organization",
        REPTEXT: "SOrg.",
        SCRTEXT_S: "Sales org.",
        SCRTEXT_M: "Sales Org.",
        SCRTEXT_L: "Sales Organization",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "VKORG",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "CC_VBELN",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "02",
        SHLPLISPOS: "02",
        DEFAULTVAL: "VKO",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "KUNNR",
        LANGU: "E",
        POSITION: 3,
        OFFSET: 84,
        DOMNAME: "KUNNR",
        ROLLNAME: "KUNAG",
        CHECKTABLE: "KNA1",
        LENG: 10,
        INTLEN: 20,
        OUTPUTLEN: 10,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "VAG",
        LOGFLAG: "X",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "ALPHA",
        HEADLEN: 10,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Sold-to party",
        REPTEXT: "Sold-to pt",
        SCRTEXT_S: "Sold-to pt",
        SCRTEXT_M: "Sold-to party",
        SCRTEXT_L: "Sold-to party",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "KUNNR",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "03",
        SHLPLISPOS: "03",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "VTWEG",
        LANGU: "E",
        POSITION: 4,
        OFFSET: 104,
        DOMNAME: "VTWEG",
        ROLLNAME: "VTWEG",
        CHECKTABLE: "TVKOV",
        LENG: 2,
        INTLEN: 4,
        OUTPUTLEN: 2,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "VTW",
        LOGFLAG: "X",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 4,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Distribution Channel",
        REPTEXT: "DChl",
        SCRTEXT_S: "Distr. Chl",
        SCRTEXT_M: "Distr. Channel",
        SCRTEXT_L: "Distribution Channel",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "VTWEG",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "04",
        SHLPLISPOS: "04",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "SPART",
        LANGU: "E",
        POSITION: 5,
        OFFSET: 108,
        DOMNAME: "SPART",
        ROLLNAME: "SPART",
        CHECKTABLE: "TVTA",
        LENG: 2,
        INTLEN: 4,
        OUTPUTLEN: 2,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "SPA",
        LOGFLAG: "X",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 2,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Division",
        REPTEXT: "Dv",
        SCRTEXT_S: "Division",
        SCRTEXT_M: "Division",
        SCRTEXT_L: "Division",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "SPART",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "05",
        SHLPLISPOS: "05",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "VKBUR",
        LANGU: "E",
        POSITION: 6,
        OFFSET: 112,
        DOMNAME: "VKBUR",
        ROLLNAME: "VKBUR",
        CHECKTABLE: "TVKBZ",
        LENG: 4,
        INTLEN: 8,
        OUTPUTLEN: 4,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "VKB",
        LOGFLAG: "X",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 5,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Sales office",
        REPTEXT: "SOff.",
        SCRTEXT_S: "Sales off.",
        SCRTEXT_M: "Sales office",
        SCRTEXT_L: "Sales office",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "VKBUR",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "06",
        SHLPLISPOS: "06",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "VKGRP",
        LANGU: "E",
        POSITION: 7,
        OFFSET: 120,
        DOMNAME: "VKGRP",
        ROLLNAME: "VKGRP",
        CHECKTABLE: "TVBVK",
        LENG: 3,
        INTLEN: 6,
        OUTPUTLEN: 3,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "VKG",
        LOGFLAG: "X",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 4,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Sales group",
        REPTEXT: "SGrp",
        SCRTEXT_S: "Sales grp",
        SCRTEXT_M: "Sales group",
        SCRTEXT_L: "Sales group",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "VKGRP",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "07",
        SHLPLISPOS: "07",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "ERNAM",
        LANGU: "E",
        POSITION: 8,
        OFFSET: 126,
        DOMNAME: "USNAM",
        ROLLNAME: "ERNAM",
        CHECKTABLE: "",
        LENG: 12,
        INTLEN: 24,
        OUTPUTLEN: 12,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "",
        LOGFLAG: "",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 12,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Name of Person who Created the Object",
        REPTEXT: "Created by",
        SCRTEXT_S: "Created",
        SCRTEXT_M: "Created by",
        SCRTEXT_L: "Created by",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "",
        COMPTYPE: "E",
        LFIELDNAME: "ERNAM",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "08",
        SHLPLISPOS: "08",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "AUART",
        LANGU: "E",
        POSITION: 9,
        OFFSET: 150,
        DOMNAME: "AUART",
        ROLLNAME: "AUART",
        CHECKTABLE: "TVAK",
        LENG: 4,
        INTLEN: 8,
        OUTPUTLEN: 4,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "AAT",
        LOGFLAG: "",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "AUART",
        HEADLEN: 4,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Sales Document Type",
        REPTEXT: "SaTy",
        SCRTEXT_S: "SalesDocTy",
        SCRTEXT_M: "Sales doc. type",
        SCRTEXT_L: "Sales document type",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "AUART",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "09",
        SHLPLISPOS: "09",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "BSTDK",
        LANGU: "E",
        POSITION: 10,
        OFFSET: 158,
        DOMNAME: "DATUM",
        ROLLNAME: "BSTDK",
        CHECKTABLE: "",
        LENG: 8,
        INTLEN: 16,
        OUTPUTLEN: 10,
        DECIMALS: 0,
        DATATYPE: "DATS",
        INTTYPE: "D",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "",
        LOGFLAG: "X",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 10,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Customer purchase order date",
        REPTEXT: "PO date",
        SCRTEXT_S: "PO date",
        SCRTEXT_M: "PO date",
        SCRTEXT_L: "Purchase order date",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "BSTDK",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "10",
        SHLPLISPOS: "10",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "TRVOG",
        LANGU: "E",
        POSITION: 11,
        OFFSET: 174,
        DOMNAME: "TRVOG",
        ROLLNAME: "TRVOG",
        CHECKTABLE: "",
        LENG: 1,
        INTLEN: 2,
        OUTPUTLEN: 1,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "VTV",
        LOGFLAG: "",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 3,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Transaction group",
        REPTEXT: "TrG",
        SCRTEXT_S: "Trans.Grp",
        SCRTEXT_M: "Transact.group",
        SCRTEXT_L: "Transaction group",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "X",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "TRVOG",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "CC_VBELN",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "11",
        SHLPLISPOS: "11",
        DEFAULTVAL: "VTV",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "POSNR",
        LANGU: "E",
        POSITION: 12,
        OFFSET: 176,
        DOMNAME: "POSNR",
        ROLLNAME: "POSNR",
        CHECKTABLE: "VBUP",
        LENG: 6,
        INTLEN: 12,
        OUTPUTLEN: 6,
        DECIMALS: 0,
        DATATYPE: "NUMC",
        INTTYPE: "N",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "M_VMVAA",
        AUTHORID: "",
        MEMORYID: "",
        LOGFLAG: "",
        MASK: "",
        MASKLEN: "0000",
        CONVEXIT: "",
        HEADLEN: 6,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Item number of the SD document",
        REPTEXT: "Item",
        SCRTEXT_S: "Item",
        SCRTEXT_M: "Item",
        SCRTEXT_L: "Item (SD)",
        KEYFLAG: "X",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "X",
        COMPTYPE: "E",
        LFIELDNAME: "POSNR",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "",
        TOPSHLPFLD: "",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "",
        SHLPSELPOS: "13",
        SHLPLISPOS: "13",
        DEFAULTVAL: "",
      },
      {
        TABNAME: "M_VMVAA",
        FIELDNAME: "VBELN",
        LANGU: "E",
        POSITION: 13,
        OFFSET: 188,
        DOMNAME: "VBELN",
        ROLLNAME: "VBELN",
        CHECKTABLE: "",
        LENG: 10,
        INTLEN: 20,
        OUTPUTLEN: 10,
        DECIMALS: 0,
        DATATYPE: "CHAR",
        INTTYPE: "C",
        REFTABLE: "",
        REFFIELD: "",
        PRECFIELD: "VBELN",
        AUTHORID: "",
        MEMORYID: "AUN",
        LOGFLAG: "",
        MASK: "  X",
        MASKLEN: "0000",
        CONVEXIT: "ALPHA",
        HEADLEN: 10,
        SCRLEN1: 10,
        SCRLEN2: 15,
        SCRLEN3: 20,
        FIELDTEXT: "Sales and Distribution Document Number",
        REPTEXT: "Document",
        SCRTEXT_S: "SD Doc.",
        SCRTEXT_M: "Sales document",
        SCRTEXT_L: "Sales document",
        KEYFLAG: "",
        LOWERCASE: "",
        MAC: "",
        GENKEY: "",
        NOFORKEY: "",
        VALEXI: "",
        NOAUTHCH: "",
        SIGN: "",
        DYNPFLD: "X",
        F4AVAILABL: "",
        COMPTYPE: "D",
        LFIELDNAME: "",
        LTRFLDDIS: "",
        BIDICTRLC: "",
        OUTPUTSTYLE: "00",
        NOHISTORY: "",
        AMPMFORMAT: "",
        TOPSHLPNAM: "CC_VBELN",
        TOPSHLPFLD: "VBELN",
        PARVA: "",
        PARTXT: "",
        SHLPOUTPUT: "X",
        SHLPSELPOS: "12",
        SHLPLISPOS: "12",
        DEFAULTVAL: "",
      },
    ]);
  });

  test("Multi-output", async () => {
    expect.assertions(2);

    shlpname = "SH H_T001";

    const desc = (await VI.getShlpDescriptor({ type: "SH", name: "H_T001" }))[
      "SH H_T001"
    ];

    expect(desc.SHLPOUTPUT).toEqual("BUKRS");
    expect(desc.ALLOUTPUTS).toEqual(["BUKRS", "BUTXT", "ORT01", "WAERS"]);
  });
});
