BAPI_USER_GET_DETAIL:
  USERNAME:
    PARAMCLASS: I
    TABNAME: BAPIBNAME
    FIELDNAME: BAPIBNAME
    PARAMTEXT: User Name
    functionName: BAPI_USER_GET_DETAIL
    paramName: USERNAME
    required: true
    paramType: var
  CACHE_RESULTS:
    PARAMCLASS: I
    TABNAME: FLAG_X
    PARAMTEXT: Temporarily buffer results in work process
    functionName: BAPI_USER_GET_DETAIL
    paramName: CACHE_RESULTS
    required: false
    default: '''X'''
    paramType: var
  RETURN:
    PARAMCLASS: T
    TABNAME: BAPIRET2
    PARAMTEXT: Return Structure
    functionName: BAPI_USER_GET_DETAIL
    paramName: RETURN
    required: true
    paramType: table
  ACTIVITYGROUPS:
    PARAMCLASS: T
    TABNAME: BAPIAGR
    PARAMTEXT: Activity Groups
    functionName: BAPI_USER_GET_DETAIL
    paramName: ACTIVITYGROUPS
    required: false
    default: ''
    paramType: table
  ADDCOMREM:
    PARAMCLASS: T
    TABNAME: BAPICOMREM
    PARAMTEXT: BAPI Structure Communication Comments
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDCOMREM
    required: false
    default: ''
    paramType: table
  ADDFAX:
    PARAMCLASS: T
    TABNAME: BAPIADFAX
    PARAMTEXT: BAPI Structure Fax Numbers
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDFAX
    required: false
    default: ''
    paramType: table
  ADDPAG:
    PARAMCLASS: T
    TABNAME: BAPIADPAG
    PARAMTEXT: BAPI Structure Pager Numbers
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDPAG
    required: false
    default: ''
    paramType: table
  ADDPRT:
    PARAMCLASS: T
    TABNAME: BAPIADPRT
    PARAMTEXT: BAPI Structure Printer Addresses
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDPRT
    required: false
    default: ''
    paramType: table
  ADDRFC:
    PARAMCLASS: T
    TABNAME: BAPIADRFC
    PARAMTEXT: BAPI Structure RFC Addresses
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDRFC
    required: false
    default: ''
    paramType: table
  ADDRML:
    PARAMCLASS: T
    TABNAME: BAPIADRML
    PARAMTEXT: Inhouse Mail BAPI Structure
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDRML
    required: false
    default: ''
    paramType: table
  ADDSMTP:
    PARAMCLASS: T
    TABNAME: BAPIADSMTP
    PARAMTEXT: E-Mail Addresses BAPI Structure
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDSMTP
    required: false
    default: ''
    paramType: table
  ADDSSF:
    PARAMCLASS: T
    TABNAME: BAPIADSSF
    PARAMTEXT: BAPI Structure SSF Addresses
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDSSF
    required: false
    default: ''
    paramType: table
  ADDTEL:
    PARAMCLASS: T
    TABNAME: BAPIADTEL
    PARAMTEXT: BAPI Structure Telephone Numbers
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDTEL
    required: false
    default: ''
    paramType: table
  ADDTLX:
    PARAMCLASS: T
    TABNAME: BAPIADTLX
    PARAMTEXT: BAPI Structure Telex Numbers
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDTLX
    required: false
    default: ''
    paramType: table
  ADDTTX:
    PARAMCLASS: T
    TABNAME: BAPIADTTX
    PARAMTEXT: BAPI Structure Teletex Numbers
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDTTX
    required: false
    default: ''
    paramType: table
  ADDURI:
    PARAMCLASS: T
    TABNAME: BAPIADURI
    PARAMTEXT: 'BAPI Structure: URL, FTP, and so on'
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDURI
    required: false
    default: ''
    paramType: table
  ADDX400:
    PARAMCLASS: T
    TABNAME: BAPIADX400
    PARAMTEXT: BAPI Structure X400 Addresses
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDX400
    required: false
    default: ''
    paramType: table
  EXTIDHEAD:
    PARAMCLASS: T
    TABNAME: BAPIUSEXTIDHEAD
    PARAMTEXT: Header Data for External ID of a User
    functionName: BAPI_USER_GET_DETAIL
    paramName: EXTIDHEAD
    required: false
    default: ''
    paramType: table
  EXTIDPART:
    PARAMCLASS: T
    TABNAME: BAPIUSEXTIDPART
    PARAMTEXT: Part of a Long Field for the External ID of a User
    functionName: BAPI_USER_GET_DETAIL
    paramName: EXTIDPART
    required: false
    default: ''
    paramType: table
  GROUPS:
    PARAMCLASS: T
    TABNAME: BAPIGROUPS
    PARAMTEXT: Transfer Structure for a List of User Groups
    functionName: BAPI_USER_GET_DETAIL
    paramName: GROUPS
    required: false
    default: ''
    paramType: table
  PARAMETER:
    PARAMCLASS: T
    TABNAME: BAPIPARAM
    PARAMTEXT: Table with User Parameters
    functionName: BAPI_USER_GET_DETAIL
    paramName: PARAMETER
    required: false
    default: ''
    paramType: table
  PARAMETER1:
    PARAMCLASS: T
    TABNAME: BAPIPARAM1
    PARAMTEXT: Replaces Parameter (Length 18 -> 40)
    functionName: BAPI_USER_GET_DETAIL
    paramName: PARAMETER1
    required: false
    default: ''
    paramType: table
  PROFILES:
    PARAMCLASS: T
    TABNAME: BAPIPROF
    PARAMTEXT: Profiles
    functionName: BAPI_USER_GET_DETAIL
    paramName: PROFILES
    required: false
    default: ''
    paramType: table
  SYSTEMS:
    PARAMCLASS: T
    TABNAME: BAPIRCVSYS
    PARAMTEXT: BAPI Structure for CUA Target Systems
    functionName: BAPI_USER_GET_DETAIL
    paramName: SYSTEMS
    required: false
    default: ''
    paramType: table
  UCLASSSYS:
    PARAMCLASS: T
    TABNAME: BAPIUCLASSSYS
    PARAMTEXT: System-Specific License-Related User Classification
    functionName: BAPI_USER_GET_DETAIL
    paramName: UCLASSSYS
    required: false
    default: ''
    paramType: table
  ADDRESS:
    PARAMCLASS: E
    TABNAME: BAPIADDR3
    PARAMTEXT: Address Data
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADDRESS
    required: true
    paramType: struct
  ADMINDATA:
    PARAMCLASS: E
    TABNAME: BAPIUSERADMIN
    PARAMTEXT: 'User: Administration Data'
    functionName: BAPI_USER_GET_DETAIL
    paramName: ADMINDATA
    required: true
    paramType: struct
  ALIAS:
    PARAMCLASS: E
    TABNAME: BAPIALIAS
    PARAMTEXT: User Name Alias
    functionName: BAPI_USER_GET_DETAIL
    paramName: ALIAS
    required: true
    paramType: struct
  COMPANY:
    PARAMCLASS: E
    TABNAME: BAPIUSCOMP
    PARAMTEXT: Company for Company Address
    functionName: BAPI_USER_GET_DETAIL
    paramName: COMPANY
    required: true
    paramType: struct
  DEFAULTS:
    PARAMCLASS: E
    TABNAME: BAPIDEFAUL
    PARAMTEXT: Structure with User Defaults
    functionName: BAPI_USER_GET_DETAIL
    paramName: DEFAULTS
    required: true
    paramType: struct
  DESCRIPTION:
    PARAMCLASS: E
    TABNAME: BAPIUSDESC
    PARAMTEXT: Description
    functionName: BAPI_USER_GET_DETAIL
    paramName: DESCRIPTION
    required: true
    paramType: struct
  IDENTITY:
    PARAMCLASS: E
    TABNAME: BAPIIDENTITY
    PARAMTEXT: Person Assignment of an Identity
    functionName: BAPI_USER_GET_DETAIL
    paramName: IDENTITY
    required: true
    paramType: struct
  ISLOCKED:
    PARAMCLASS: E
    TABNAME: BAPISLOCKD
    PARAMTEXT: User Lock
    functionName: BAPI_USER_GET_DETAIL
    paramName: ISLOCKED
    required: true
    paramType: struct
  LASTMODIFIED:
    PARAMCLASS: E
    TABNAME: BAPIMODDAT
    PARAMTEXT: 'User: Last Change (Date and Time)'
    functionName: BAPI_USER_GET_DETAIL
    paramName: LASTMODIFIED
    required: true
    paramType: struct
  LOGONDATA:
    PARAMCLASS: E
    TABNAME: BAPILOGOND
    PARAMTEXT: Structure with Logon Data
    functionName: BAPI_USER_GET_DETAIL
    paramName: LOGONDATA
    required: true
    paramType: struct
  REF_USER:
    PARAMCLASS: E
    TABNAME: BAPIREFUS
    PARAMTEXT: User Name of the Reference User
    functionName: BAPI_USER_GET_DETAIL
    paramName: REF_USER
    required: true
    paramType: struct
  SNC:
    PARAMCLASS: E
    TABNAME: BAPISNCU
    PARAMTEXT: Secure Network Communication Data
    functionName: BAPI_USER_GET_DETAIL
    paramName: SNC
    required: true
    paramType: struct
  UCLASS:
    PARAMCLASS: E
    TABNAME: BAPIUCLASS
    PARAMTEXT: License-Related User Classification
    functionName: BAPI_USER_GET_DETAIL
    paramName: UCLASS
    required: true
    paramType: struct
STFC_CONNECTION:
  REQUTEXT:
    PARAMCLASS: I
    TABNAME: SYST
    FIELDNAME: LISEL
    PARAMTEXT: ''
    functionName: STFC_CONNECTION
    paramName: REQUTEXT
    required: true
    paramType: var
  ECHOTEXT:
    PARAMCLASS: E
    TABNAME: SYST
    FIELDNAME: LISEL
    PARAMTEXT: ''
    functionName: STFC_CONNECTION
    paramName: ECHOTEXT
    required: true
    paramType: var
  RESPTEXT:
    PARAMCLASS: E
    TABNAME: SYST
    FIELDNAME: LISEL
    PARAMTEXT: ''
    functionName: STFC_CONNECTION
    paramName: RESPTEXT
    required: true
    paramType: var
STFC_PERFORMANCE:
  CHECKTAB:
    PARAMCLASS: I
    TABNAME: SYST
    FIELDNAME: INPUT
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: CHECKTAB
    required: true
    paramType: var
  LGET0332:
    PARAMCLASS: I
    TABNAME: OAPRI
    FIELDNAME: APAGE
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: LGET0332
    required: true
    paramType: var
  LGET1000:
    PARAMCLASS: I
    TABNAME: OAPRI
    FIELDNAME: APAGE
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: LGET1000
    required: true
    paramType: var
  LGIT0332:
    PARAMCLASS: I
    TABNAME: OAPRI
    FIELDNAME: APAGE
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: LGIT0332
    required: true
    paramType: var
  LGIT1000:
    PARAMCLASS: I
    TABNAME: OAPRI
    FIELDNAME: APAGE
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: LGIT1000
    required: true
    paramType: var
  ETAB0332:
    PARAMCLASS: T
    TABNAME: H332
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: ETAB0332
    required: true
    paramType: table
  ETAB1000:
    PARAMCLASS: T
    TABNAME: H1000
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: ETAB1000
    required: true
    paramType: table
  ITAB0332:
    PARAMCLASS: T
    TABNAME: H332
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: ITAB0332
    required: true
    paramType: table
  ITAB1000:
    PARAMCLASS: T
    TABNAME: H1000
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: ITAB1000
    required: true
    paramType: table
  EXITCODE:
    PARAMCLASS: E
    TABNAME: SYST
    FIELDNAME: INPUT
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: EXITCODE
    required: true
    paramType: var
  TEXT0332:
    PARAMCLASS: E
    TABNAME: SYST
    FIELDNAME: ENTRY
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: TEXT0332
    required: true
    paramType: var
  TEXT1000:
    PARAMCLASS: E
    TABNAME: SYST
    FIELDNAME: ENTRY
    PARAMTEXT: ''
    functionName: STFC_PERFORMANCE
    paramName: TEXT1000
    required: true
    paramType: var
