# prettier-ignore

_test:
  - /coe/rbp_fe_datatypes
  - /coe/rbp_fe_datatypes2

api.equipment:
  - /COE/RBP_PAM_EQUIPMENT_GETL
  - /COE/RBP_PAM_EQUIPMENT_GET
  - /COE/RBP_PAM_EQUIPMENT_CHANGE
  - BAPI_EQUI_CREATE
  - /COE/RBP_PAM_EQUIPMENT_INSTALL
  - /COE/RBP_PAM_EQUIPMENT_DISMTLE
  - /COE/RBP_PAM_EQUIP_HIER_GET

api.serviceOrder:
  - /COE/RBP_PAM_SERVICE_ORD_CREAT # Create one instance of Service Order object
  - /COE/RBP_PAM_SERV_ORD_CREAT_N # Create Service Order from Notification
  - /COE/RBP_PAM_SERVICE_ORD_GET # Get details of one Service Order object
  - /COE/RBP_PAM_SERVICE_ORD_CC # Calculate costs of one instance of Service Order object
  - /COE/RBP_PAM_SERVICE_ORD_GETL # Get a Service Orders' list
  - /COE/RBP_PAM_SERVICE_ORD_CHANG # Change one instance of Service Order object

api.serviceNotification:
  - /COE/RBP_PAM_NOTIFICATION_GET # get detail of notification
  - /COE/RBP_PAM_NOTIFICATION_GETL # Get notification header list
  - /COE/RBP_PAM_NOTIF_CHANGE # change notification
  - /COE/RBP_PAM_NOTIF_CREATE # create notification

api.purchaseOrder:
  # 10502                        APS Procurement Order
  #- BAPI_POSRVAPS_COMPLETEKEY    # Assignment of External Keys to Internal Keys
  #- BAPI_POSRVAPS_CREATESNPORDER # Create or Change Stock Transfers or Purchase Requisitions for SNP
  #- BAPI_POSRVAPS_DELMULTI       # Delete One or More Procurement Orders
  #- BAPI_POSRVAPS_GETLIST3       # Read Procurement Orders for Selection Criteria - With Characteristics
  #- BAPI_POSRVAPS_REMOVEITEMS    # Delete one or more Procurement Items / Schedule Lines
  #- BAPI_POSRVAPS_REQUESTLIST2   # Request: Read Procurement Orders for Selection Criteria
  #- BAPI_POSRVAPS_SAVEMULTI3     # Create and Change External Procurement Orders/Items/Schedule Lines

  # 10502IF                        Procurement Order APS Receiver
  # [not in MME] BAPI_POSRVAPSIF_RECEIVELIST2 # Receipt of Request Result: Procurement Order Selection

  # 2012                         BAPI in the Enjoy Purchase Order
  - BAPI_PO_CHANGE               # Change Purchase Order
  - BAPI_PO_CREATE1              # Create Purchase Order
  - BAPI_PO_GETDETAIL1           # Detail Information for a Purchase Order

  # MELE                         Interface: Purchasing - Delivery
  - BAPI_PO_DELETE_HISTORY       # Delete Purchase Order History
  - BAPI_PO_UPDATE_HISTORY       # Update Purchase Order (Update, Insert)

  # MEWF                         BAPIs for Release of Requisition/PO
  - BAPI_PO_RELEASE              # Release Purchase Orders
  - BAPI_PO_RESET_RELEASE        # Cancel Release of Purchase Orders

  # MEWP                         BAPIs Purchase order
  # [old] BAPI_PO_CREATE         # Create Purchase Order
  # [old] BAPI_PO_GETDETAIL      # Display Purchase Order Details
  - BAPI_PO_GETITEMS             # List Purchase Order Items
  - BAPI_PO_GETITEMSREL          # List Purchase Orders for Release (Approval): New as of 4.0A
  - BAPI_PO_GETRELINFO           # Display Detailed Release (Approval) Information on Purchase Order
  - BAPI_PO_GET_LIST             # List Purchase Orders - Only up to 4.0A

  # VVA01                        Separation of Purchasing and Accounting
  - BAPI_POACCPART_CREATE        # Create FI-Purchase Order
# businessPartner:
#   - BAPI_BUSPARTNER_CHANGE
#   - BAPI_BUSPARTNER_CREATE
#   - BAPI_BUSPARTNER_GETDETAIL
#   - BAPI_BUSPARTNER_GETLIST
#   - BAPI_BUSPARTNER_GETLISTCUST
#   - BAPI_BUSPARTNER_GETLISTEMPL
#   - BAPI_BUSPARTNER_GETLISTHOSP
#   - BAPI_BUSPARTNER_GETLISTINSPROV
#   - BAPI_BUSPARTNER_GETLISTPERSON

# personalData:
#   - BAPI_PERSDATA_CHANGE
#   - BAPI_PERSDATA_CREATE
#   - BAPI_PERSDATA_CREATESUCCESSOR
#   - BAPI_PERSDATA_DELETE
#   - BAPI_PERSDATA_DELIMIT
#   - BAPI_PERSDATA_GETDETAIL
#   - BAPI_PERSDATA_GETDETAILEDLIST
#   - BAPI_PERSDATA_GETLIST
#   - BAPI_PERSDATA_SIMULATECREATION

# equipment:
#   - BAPI_EQUI_CHANGE # Change Equipment
#   - BAPI_EQUI_CREATE # Create Equipment
#   - BAPI_EQUI_CREATE_BY_REFERENCE # Anlegen Equipment mit Vorlageequipment
#   - BAPI_EQUI_DISMANTLE # Install Equipment (Functional Location, Superior Equipment)
#   - BAPI_EQUI_GETDETAIL # Read Equipment
#   - BAPI_EQUI_GETLIST # Selection of Equipment List
#   - BAPI_EQUI_GETSTATUS # Read (System-/User-)Status Equi
#   - BAPI_EQUI_INSTALL # Install Equipment (Functional Location, Superior Equipment)

# workOrder:
#   - BAPI_ALM_COMPONENT_GET_DETAIL
#   - BAPI_ALM_OPERATION_GET_DETAIL
#   - BAPI_ALM_ORDERHEAD_GET_LIST
#   - BAPI_ALM_ORDEROPER_GET_LIST
#   - BAPI_ALM_ORDER_GET_DETAIL
#   - BAPI_ALM_ORDER_MAINTAIN

# workOrderConfirmation:
#   - BAPI_ALM_CONF_CANCEL
#   - BAPI_ALM_CONF_CREATE
#   - BAPI_ALM_CONF_GETDETAIL
#   - BAPI_ALM_CONF_GETLIST
#   - BAPI_ALM_GET_PROP

# PMCSnotification:
#   - BAPI_ALM_NOTIF_CHANGEUSRSTAT
#   - BAPI_ALM_NOTIF_CLOSE
#   - BAPI_ALM_NOTIF_CREATE
#   - BAPI_ALM_NOTIF_DATA_ADD
#   - BAPI_ALM_NOTIF_DATA_DELETE
#   - BAPI_ALM_NOTIF_DATA_MODIFY
#   - BAPI_ALM_NOTIF_GET_DETAIL
#   - BAPI_ALM_NOTIF_LIST_EQUI
#   - BAPI_ALM_NOTIF_LIST_FUNCLOC
#   - BAPI_ALM_NOTIF_LIST_PARTNER
#   - BAPI_ALM_NOTIF_LIST_PLANGROUP
#   - BAPI_ALM_NOTIF_LIST_SORTFIELD
#   - BAPI_ALM_NOTIF_POSTPONE
#   - BAPI_ALM_NOTIF_PUTINPROGRESS
#   - BAPI_ALM_NOTIF_SAVE
#   - BAPI_ALM_NOTIF_TASK_COMPLETE
#   - BAPI_ALM_NOTIF_TASK_RELEASE
#   - BAPI_ALM_NOTIF_TASK_SUCCESS

# serviceMasterRecord:
#   - BAPI_SERVICE_CHANGE
#   - BAPI_SERVICE_CREATE
#   - BAPI_SERVICE_GET_DETAIL
#   - BAPI_SERVICE_GET_LIST

# inspectionLot:
#   - BAPI_INSPCHAR_GETREQUIREMENTS
#   - BAPI_INSPCHAR_GETRESULT
#   - BAPI_INSPCHAR_SETRESULT
#   - BAPI_INSPLOT_GETDETAIL
#   - BAPI_INSPLOT_GETLIST
#   - BAPI_INSPLOT_GETOPERATIONS
#   - BAPI_INSPLOT_GETSTATUS
#   - BAPI_INSPLOT_SETUSAGEDECISION
#   - BAPI_INSPOPER_ACKNOWLEDGE
#   - BAPI_INSPOPER_GETCHAR
#   - BAPI_INSPOPER_GETDETAIL
#   - BAPI_INSPOPER_GETLIST
#   - BAPI_INSPOPER_RECORDRESULTS
#   - BAPI_INSPPOINT_CHANGE
#   - BAPI_INSPPOINT_CREATEFROMDATA
#   - BAPI_INSPPOINT_GETLIST
#   - BAPI_INSPPOINT_GETREQUIREMENTS

# kanban:
#   - BAPI_KANBAN_CHANGE
#   - BAPI_KANBAN_CHANGESTATUS1
#   - BAPI_KANBAN_GETLIST
#   - BAPI_KANBAN_GETLISTFORSUPPLIE1
#   - BAPI_KANBAN_GETLIST_ALL
#   - BAPI_KANBAN_SETINPROCESS

# plannedOrder:
#   - BAPI_PLANNEDORDER_CHANGE
#   - BAPI_PLANNEDORDER_CREATE
#   - BAPI_PLANNEDORDER_DELETE
#   - BAPI_PLANNEDORDER_EXIST_CHECK
#   - BAPI_PLANNEDORDER_GET_DETAIL
#   - BAPI_PLANNEDORDER_GET_DET_LIST

# processOrder:
#   - BAPI_PROCORD_CHANGE
#   - BAPI_PROCORD_CHECK_MAT_AVAIL
#   - BAPI_PROCORD_CLOSE
#   - BAPI_PROCORD_COMPLETE_TECH
#   - BAPI_PROCORD_COSTING
#   - BAPI_PROCORD_CREATE
#   - BAPI_PROCORD_CREATE_CAP_REQ
#   - BAPI_PROCORD_CREATE_FROM_PLORD
#   - BAPI_PROCORD_CREATE_FROM_REF
#   - BAPI_PROCORD_EXIST_CHECK
#   - BAPI_PROCORD_GET_DETAIL
#   - BAPI_PROCORD_GET_LIST
#   - BAPI_PROCORD_RELEASE
#   - BAPI_PROCORD_REVOKEUSERSTATUS
#   - BAPI_PROCORD_SCHEDULE
#   - BAPI_PROCORD_SETUSERSTATUS
#   - BAPI_PROCORD_SET_DELETION_FLAG
#   - BAPI_PROCORD_SET_DEL_INDICATOR
#   - BAPI_PROCORD_WM_MAT_STAGING

# productionOrder:
#   - BAPI_PRODORD_CHANGE
#   - BAPI_PRODORD_CHECK_MAT_AVAIL
#   - BAPI_PRODORD_CLOSE
#   - BAPI_PRODORD_COMPLETE_TECH
#   - BAPI_PRODORD_COSTING
#   - BAPI_PRODORD_CREATE
#   - BAPI_PRODORD_CREATE_CAP_REQ
#   - BAPI_PRODORD_CREATE_FROM_PLORD
#   - BAPI_PRODORD_CREATE_FROM_REF
#   - BAPI_PRODORD_EXIST_CHECK
#   - BAPI_PRODORD_GET_DETAIL
#   - BAPI_PRODORD_GET_LIST
#   - BAPI_PRODORD_RELEASE
#   - BAPI_PRODORD_REVOKEUSERSTATUS
#   - BAPI_PRODORD_SCHEDULE
#   - BAPI_PRODORD_SETUSERSTATUS
#   - BAPI_PRODORD_SET_DELETION_FLAG
#   - BAPI_PRODORD_SET_DEL_INDICATOR
#   - BAPI_PRODORD_WM_MAT_STAGING

# transferOrder:
#   - BAPI_WHSE_TO_CREATE_STOCK
#   - BAPI_WHSE_TO_GET_DETAIL
#   - BAPI_WHSE_TO_GET_LIST

# transport:
#   - CTS_API_CREATE_CHANGE_REQUEST
#   - BAPI_CTREQUEST_CREATE
#   - BAPI_CTREQUEST_CREATE_TASKS

# salesOrder:
#   - BAPI_SALESORDER_CREATEFROMDAT2
#   - BAPI_SALESORDER_CHANGE
#   - BAPI_SALESORDER_GETLIST
#   - BAPISDORDER_GETDETAILEDLIST
#   - BAPI_SALESORDER_CONFIRMDELVRY
#   - BAPI_SALESORDER_GETSTATUS
#   - BAPI_SALESORDER_SIMULATE

# FI:
#   - BAPI_ACC_DOCUMENT_POST
