api.equipment:
  - /COE/RBP_PAM_EQUIPMENT_GETL # Selection of Equipment List
  - /COE/RBP_PAM_EQUIPMENT_GET # Read Equipment
  - /COE/RBP_PAM_EQUIPMENT_CHANGE # Change Equipment
  - /COE/RBP_PAM_EQUIPMENT_INSTALL # Install Equipment (Functional Location, Superior Equipment)
  - /COE/RBP_PAM_EQUIPMENT_DISMTLE # Dismantle Equipment (Functional Location, Superior Equipment)
  - /COE/RBP_PAM_EQUIP_HIER_GET # Read Equipment installation hierarchy
  - BAPI_EQUI_CREATE # Create Equipment

# Based on standard BAPIs
#   - BAPI_EQUI_CHANGE # Change Equipment
#   - BAPI_EQUI_CREATE # Create Equipment
#   - BAPI_EQUI_CREATE_BY_REFERENCE # Anlegen Equipment mit Vorlageequipment
#   - BAPI_EQUI_DISMANTLE # Install Equipment (Functional Location, Superior Equipment)
#   - BAPI_EQUI_GETDETAIL # Read Equipment
#   - BAPI_EQUI_GETLIST # Selection of Equipment List
#   - BAPI_EQUI_GETSTATUS # Read (System-/User-)Status Equi
#   - BAPI_EQUI_INSTALL # Install Equipment (Functional Location, Superior Equipment)
