api.equipment:
  - /COE/RBP_PAM_EQUIPMENT_GETL
  - /COE/RBP_PAM_EQUIPMENT_GET
  - /COE/RBP_PAM_EQUIPMENT_CHANGE
  - BAPI_EQUI_CREATE
  - /COE/RBP_PAM_EQUIPMENT_INSTALL
  - /COE/RBP_PAM_EQUIPMENT_DISMTLE
  - /COE/RBP_PAM_EQUIP_HIER_GET
