MME:
  search_help_api:
    determine: /COE/RBP_FE_SHLP_DETERM_SEARCH
    FV_descriptor_get: /COE/RBP_FE_SHLP_DOMVALUES_GET
    CT_descriptor_get: FDT_GET_DDIC_METADATA
    SH_descriptor_get: /COE/RBP_FE_SHLP_METADATA_GET
    search: /COE/RBP_FE_SHLP_GET

coevi51:
  search_help_api:
    determine: /COE/RBP_FE_SHLP_DETERM_SEARCH
    CT_descriptor_get: FDT_GET_DDIC_METADATA

10.68.110.51:
  search_help_api:
    determine: /COE/RBP_FE_SHLP_DETERM_SEARCH
    CT_descriptor_get: FDT_GET_DDIC_METADATA

I64:
  search_help_api:
    determine: YSHLP_DETERMINE_SEARCHHELP
    CT_descriptor_get: FDT_GET_DDIC_METADATA

S16-5010:
  search_help_api:
    determine: YWS_SHLP_DETERMINE
    CT_descriptor_get: FDT_GET_DDIC_METADATA
